"""create cameras table

Revision ID: b88afa310546
Revises: 43083e401745
Create Date: 2025-12-12 18:50:44.454870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b88afa310546'
down_revision: Union[str, Sequence[str], None] = '43083e401745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('puerto', sa.Integer(), nullable=False),
    sa.Column('orientacion', sa.String(length=50), nullable=True),
    sa.Column('mac', sa.String(length=50), nullable=False),
    sa.Column('patio_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip', 'deleted_at', name='uq_camera_ip_active'),
    sa.UniqueConstraint('mac', 'deleted_at', name='uq_camera_mac_active')
    )
    op.create_index(op.f('ix_cameras_ip'), 'cameras', ['ip'], unique=False)
    op.create_index(op.f('ix_cameras_mac'), 'cameras', ['mac'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cameras_mac'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_ip'), table_name='cameras')
    op.drop_table('cameras')
    # ### end Alembic commands ###
